Repository DecodersCommunity/portfolio-builder, pull requests merged in 2022-10, with the labels that each got.

#10 Added AtharveChauhan.html
  Your Portfolio/AtharveChauhan.html
  Your Portfolio/Images/AtharveChauhan.jpeg
Labels: hacktoberfest-accepted

#9 Updated Readme File
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#11 Added my portfolio
  Your Portfolio/Images/harshit-sharma-gits.png
  Your Portfolio/harshit-sharma-gits.html
Labels: hacktoberfest-accepted

#13 Uploaded Ankit's Portfolio
  Your Portfolio/AnkitMajee.html
  Your Portfolio/Images/AnkitMajee.png
Labels: hacktoberfest-accepted

#14 Created portfolio!
  Your Portfolio/Images/RajavJain.png
  Your Portfolio/RajavJain.html
Labels: hacktoberfest-accepted

#15 Edited The Content As Per The Comments #7
  Your Portfolio/Images/piyush0045.jpg
  Your Portfolio/piyush0045.html
Labels: hacktoberfest-accepted

#20 Added my portfolio
  Your Portfolio/Images/Singhmuskan11.jfif
  Your Portfolio/MuskanSingh.html
Labels: hacktoberfest-accepted

#19 Edited the inner text as instructed.
  Your Portfolio/Aniruddh-Singh.html
  Your Portfolio/Images/Aniruddh-Singh.jpg
Labels: hacktoberfest-accepted

#21 I have made the changes in the index.html file to improve the base template
  Template/index.html
Labels: hacktoberfest-accepted

#12 Added Sneha's Portfolio
  Your Portfolio/isyneha.html
Labels: hacktoberfest

#25 DEVANSH-200101028
  Template/index.html
Labels: hacktoberfest-accepted

#28 Hacktoberfest
  Your Portfolio/Cheeh1.html
  Your Portfolio/Images/Cheeh1.jpg
Labels: hacktoberfest-accepted

#29 Update mohit03nadan.html
  Your Portfolio/Images/mohit03nandan.jpg
  mohit03nandan.html
Labels: hacktoberfest-accepted

#33 title: Portfolio of Tony Stark/Rahul_learner
  Your Portfolio/Images/rahul_learner.jpg
  Your Portfolio/Rahul_learner.html
Labels: hacktoberfest-accepted

#36 added Sharmila_21.html
  Your Portfolio/Images/Sharmila_21.png
  Your Portfolio/Sharmila_21.html
Labels: hacktoberfest-accepted

#38 Added hectorpasarin portfolio
  Your Portfolio/Images/hectorpasarin.jpg
  Your Portfolio/hectorpasarin.html
Labels: hacktoberfest-accepted

#40 Added muzhda's information in protfolio builder
  Your Portfolio/Images/MuzhdaN.png
  Your Portfolio/MuzhdN.html
Labels: hacktoberfest-accepted

#41 Update README.md
  README.md
Labels: hacktoberfest-accepted

#43 added my portfolio and image to the respective folder and made fixed some bugs in which SVG's were not loading
  Your Portfolio/Images/kunalthedev.jpeg
  Your Portfolio/kunalthedev.html
Labels: hacktoberfest-accepted

#45 Added my portfolio
  Your Portfolio/210111005.jpeg
  Your Portfolio/Images/botketan.jpeg
  Your Portfolio/botketan.html
Labels: hacktoberfest-accepted

#49 Added my Portfolio
  Your Portfolio/Images/priya-sharma-gits.jpeg
  Your Portfolio/priya-sharma-gits.html
Labels: hacktoberfest-accepted

#55 Added my Portfolio
  Your Portfolio/Images/Tyagirohan.jpg
  Your Portfolio/Tyagirohan.html
Labels: hacktoberfest-accepted

#59 Added my portfolio here. Please😀
  Your Portfolio/Gautam-Developer.html
Labels: hacktoberfest-accepted

#53 Yash's portfolio
  Your Portfolio/Images/Yk.jpeg
  Your Portfolio/Yash5015.html
Labels: hacktoberfest-accepted

#51 issue number #7
  Your Portfolio/Images/Pratibha-Singh-05.jpg
  Your Portfolio/Pratibha-Singh-05.html
Labels: hacktoberfest-accepted

#56 Issue number #7
  Your Portfolio/Images/avinishrao.jpg
  Your Portfolio/avinishrao.html
Labels: hacktoberfest-accepted

#57 Create vennela2132.html
  Your Portfolio/vennela2132.html
Labels: hacktoberfest-accepted

#58 Added anikurhade Profile
  Your Portfolio/Images/anikurhade.jpg
  Your Portfolio/anikurhade.html
Labels: hacktoberfest-accepted

#48 create own portfolio
  Your Portfolio/Images/sangam-verma9.jpg
  Your Portfolio/sangam-verma9.html
Labels: hacktoberfest-accepted

#54 zoom effect in index.html
  Template/index.html
Labels: enhancement, hacktoberfest-accepted

#73 Added Nandan's Portfolio
  Your Portfolio/Zenith-Mind.html
Labels: hacktoberfest-accepted

#71 Added Code to Create a Simple Portfolio About me
  .DS_Store
  Your Portfolio/.DS_Store
  Your Portfolio/Images/radharaniraj.jpeg
  Your Portfolio/radharaniraj.html
Labels: hacktoberfest-accepted

#72 Nikita0509
  Your Portfolio/Images/Nikita0509.png
  Your Portfolio/Nikita0509.html
Labels: hacktoberfest-accepted

#62 #7
  Your Portfolio/Images/shreyavemahbtu.png.jpg
  Your Portfolio/ShreyaVermahbtu
Labels: hacktoberfest-accepted

#61 issue no : #7
  Your Portfolio/Images/pranjal.jpeg
  pddwivedi45.html
Labels: hacktoberfest-accepted

#65 Added Bhagya3009 Portfolio
  Your Portfolio/Images/bhagya30009.png
  Your Portfolio/bhagya3009.html
Labels: hacktoberfest-accepted

#63 Vishal-vedantam-gits portfolio added
  Your Portfolio/Images/vishal-vedantam-gits.jpeg
  Your Portfolio/vishal-vedantam-gits.html
Labels: hacktoberfest-accepted

#64 Added my Portfolio
  Your Portfolio/01shiwanikumari.html
  Your Portfolio/Images/01shiwanikumari.png
Labels: hacktoberfest-accepted

#69 added Vishwa's Portfolio🚀
  Your Portfolio/PakaVishwaTeja.html
Labels: hacktoberfest-accepted

#70 Varun's portfolio
  Your Portfolio/Images/vrooomy.jpg
  Your Portfolio/vrooomy.html
Labels: hacktoberfest-accepted

#68 Created and Added Aryan.html to Portfolio builder
  Your Portfolio/aryankurhade.html
Labels: hacktoberfest-accepted

#66 issue #7
  Your Portfolio/Images/rahul2001dewangan.jpg
  Your Portfolio/rahul2001dewangan.html
Labels: hacktoberfest-accepted

#60 Create Sejal-shh.html
  Your Portfolio/Sejal-shh.html
Labels: hacktoberfest-accepted

#75 added mine
  Your Portfolio/0001-19319814386_20210405_165619_0000.html
  Your Portfolio/Images/0001-19319814386_20210405_165619_0000.png
Labels: good first issue, hacktoberfest

#74 Create varshini901.html
  Your Portfolio/varshini901.html
Labels: good first issue, hacktoberfest-accepted

#76 Create amol.html
  Your Portfolio/amol.html
Labels: hacktoberfest, hacktoberfest-accepted

#77 Moved two portfolios in respective folder
  Your Portfolio/mohit03nandan.html
  Your Portfolio/pddwivedi45.html
Labels: hacktoberfest, hacktoberfest-accepted
